---
- name: Build Resources using Cloudformation
  block:
    - name: Create Temporary Template folder
      tempfile:
        state: directory
        suffix: -template
      changed_when: false
      register: template_temp_dir

    - name: Build Cloudformation template
      template:
        src: cfn_rds_postgresql.yml
        dest: "{{ template_temp_dir.path }}/cfn_rds_postgresql.yml"
      changed_when: false

    - name: Validate Cloudformation template
      cloudformation_validate:
        region: "{{ common_aws_region }}"
        template: "{{ template_temp_dir.path }}/cfn_rds_postgresql.yml"

    - name: Provision RDS PostgresQL Resource
      cloudformation:
        stack_name: "{{ rds_postgresql_stack_name }}-{{ rds_postgresql_team }}-rds-postgresql"
        state: present
        region: "{{ common_aws_region }}"
        disable_rollback: true
        template: "{{ template_temp_dir.path }}/cfn_rds_postgresql.yml"
        template_parameters:
          CidrBlock: "{{ common_cidr_block }}"
          DBName: "{{ rds_postgresql_db_name }}"
          DBUserName: "{{ rds_postgresql_db_username }}"
          TeamName: "{{ rds_postgresql_team }}"
        tags:
          Name: "{{ rds_postgresql_stack_name }}"
          team: "{{ rds_postgresql_team }}"
          environment: "{{ rds_postgresql_environment }}"
      register: rds_postgresql_cfn_result

    - name: Display Cloudformation Output
      debug:
        msg: "{{ rds_postgresql_cfn_result }}"

  always:
    - name: Cleanup Temporary Template Folder
      file:
        path: "{{ template_temp_dir.path }}"
        state: absent
      changed_when: false
