---
- name: Build Resources using Cloudformation
  block:
    - name: Create Temporary Template folder
      tempfile:
        state: directory
        suffix: -template
      changed_when: false
      register: template_temp_dir

    - name: Build Cloudformation template
      template:
        src: cfn_load_balancer.yml
        dest: "{{ template_temp_dir.path }}/cfn_load_balancer.yml"
      changed_when: false

    - name: Validate Cloudformation template
      cloudformation_validate:
        region: "{{ common_aws_region }}"
        template: "{{ template_temp_dir.path }}/cfn_load_balancer.yml"

    - name: Provision Application LoadBalancer Resources
      cloudformation:
        stack_name: "{{ load_balancer_stack_name }}-{{ load_balancer_team }}-app-loadbalancer"
        state: present
        region: "{{ common_aws_region }}"
        disable_rollback: true
        template: "{{ template_temp_dir.path }}/cfn_load_balancer.yml"
        template_parameters:
          CidrBlock: "{{ common_cidr_block }}"
          CidrWhitelist: "{{ common_cidr_whitelist }}"
          TeamName: "{{ load_balancer_team }}"
        tags:
          Name: "{{ load_balancer_stack_name }}"
          team: "{{ load_balancer_team }}"
          environment: "{{ load_balancer_environment }}"
      register: load_balancer_cfn_result

    - name: Display Cloudformation Output
      debug:
        msg: "{{ load_balancer_cfn_result }}"

  always:
    - name: Cleanup Temporary Template Folder
      file:
        path: "{{ template_temp_dir.path }}"
        state: absent
      changed_when: false
