---
- name: Build Resources using Cloudformation
  block:
    - name: Create Temporary Template Folder
      tempfile:
        state: directory
        suffix: -template
      changed_when: false
      register: template_temp_dir

    - name: Build Cloudformation template
      template:
        src: cfn_vpc.yml
        dest: "{{ template_temp_dir.path }}/cfn_vpc.yml"
      changed_when: False

    - name: Validate CloudFormation template
      cloudformation_validate:
        region: "{{ common_aws_region }}"
        template: "{{ template_temp_dir.path }}/cfn_vpc.yml"

    - name: Provision VPC Resource
      cloudformation:
        stack_name: "{{ vpc_stack_name }}-{{ vpc_team }}-vpc"
        state: present
        region: "{{ common_aws_region }}"
        disable_rollback: true
        template: "{{ template_temp_dir.path }}/cfn_vpc.yml"
        template_parameters:
          CidrBlock: "{{ common_cidr_block }}"
          CidrWhitelist: "{{ common_cidr_whitelist }}"
          TeamName: "{{ vpc_team }}"
        tags:
          Name: "{{ vpc_stack_name }}"
          team: "{{ vpc_team }}"
          environment: "{{ vpc_environment }}"
      register: vpc_cfn_result

    - name: Display Cloudformation Output
      debug:
        msg: "{{ vpc_cfn_result }}"

  always:
    - name: Cleanup Temporary Template Folder
      file:
        path: "{{ template_temp_dir.path }}"
        state: absent
      changed_when: false
