---
AWSTemplateFormatVersion: "2010-09-09"
Description: Provision VPC

Parameters:
  CidrBlock:
    Description: The CIDR Range to be created
    Type: String
  TeamName:
    Description: The Team who owns this stack
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: false
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Sub ${TeamName}-vpc

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${TeamName}-internet-gateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${TeamName}-route-table

  Route:
    Type: AWS::EC2::Route
    DependsOn:
      - InternetGateway
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTable

  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub ${AWS::Region}a
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${TeamName}-subnet

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet

  S3Endpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      PolicyDocument: {
        "Version":"2012-10-17",
        "Statement":[{
          "Effect":"Allow",
          "Principal": "*",
          "Action":["*"],
          "Resource":["*"]
        }]
      }
      RouteTableIds:
        - !Ref RouteTable
      ServiceName:
        !Sub com.amazonaws.${AWS::Region}.s3
      VpcId: !Ref VPC

  S3BucketFlowLog:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Sub vpc-flow-logs-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  VPCFlowLog:
    Type: AWS::EC2::FlowLog
    Properties:
      LogDestination: !GetAtt S3BucketFlowLog.Arn
      LogDestinationType: s3
      ResourceId: !Ref VPC
      ResourceType: VPC
      TrafficType: ALL

Outputs:
  S3BucketFlowLog:
    Description: The S3 Bucket holding vpc flow logs
    Value: !Ref S3BucketFlowLog
    Export:
      Name: !Sub "${TeamName}-s3-flow-logs"
  
  ExternalSubnet:
    Description: External Subnet
    Value: !Ref Subnet
    Export:
      Name: !Sub "${TeamName}-external-app-subnet"
