---
AWSTemplateFormatVersion: "2010-09-09"
Description: Provision VPC

Parameters:
  CidrBlock:
    Description: The CIDR Range to be created
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: false
      InstanceTenancy: default
